#include <sys/types.h>

struct specter_args
{
    void* dlsym;
    int* pipe;
    int* rwpair;
    uint64_t kpipe_addr;
    uint64_t kdata_base;
    int* retval;
};

uint64_t _start(void* dlsym, int master, int victim, uint64_t pktopts, uint64_t kdata_base);

/*
 * p_syscall: cached syscall instruction address used by common_syscall
 * (generated by syscalls-ps5.py). Pre-setting it avoids the dlsym-based
 * resolution path in common_syscall, which would infinite-recurse when
 * the ps5-payload-dev elfldr passes getpid (not dlsym) at args->dlsym.
 *
 * On PS5 libkernel, syscall stubs are: mov rax, <nr>; mov r10, rcx; syscall
 * The mov rax is 7 bytes (REX.W + opcode + imm32), so +7 = mov r10, rcx; syscall.
 * common_syscall sets its own rax before jumping here, so this is correct.
 */
extern uint64_t p_syscall;

void elf_main(struct specter_args* args)
{
    /* Pre-set p_syscall from the function pointer at args->dlsym.
     * The elfldr passes getpid here (not dlsym). getpid+7 points to
     * "mov r10, rcx; syscall" which is the generic syscall entry point.
     * This must happen before _start, which triggers syscalls via
     * r0gdb_init -> set_offsets -> sysctl. */
    if (!p_syscall)
        p_syscall = (uint64_t)args->dlsym + 7;

    *args->retval = _start(args->dlsym, args->rwpair[0], args->rwpair[1], 0, args->kdata_base);
}
